### ISSUE TITLE
.travis-ci.yml file configuration

### ISSUE THREAD

**Issue by ljmf00** [vigiloproject/vigilo#10]
# Travis-CI Tester
 - [ ] **Need to configure .travis-ci file**

For .travis-ci.yml file build, follow this file example:
``` yml
# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to 5.2.17
  - 5.2
  # aliased to 5.3.29
  - 5.3
  # aliased to a recent 5.4.x version
  - 5.4
  # aliased to a recent 5.5.x version
  - 5.5
  # aliased to a recent 5.6.x version
  - 5.6
  # aliased to a recent 7.x version
  - 7.0
  # aliased to a recent hhvm version
  - hhvm

# optionally specify a list of environments, for example to test different RDBMS
env:
  - DB=mysql
  - DB=pgsql

# optionally set up exclutions and allowed failures in the matrix
matrix:
  exclude:
    - php: hhvm
      env: DB=pgsql  # PDO driver for pgsql is unsupported by HHVM (3rd party install for support)
  allow_failures:
    - php: 7.0
    - php: hhvm

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS hello_world_test;" -U postgres; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database hello_world_test;" -U postgres; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hello_world_test;" -uroot; fi

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: phpunit --configuration phpunit_$DB.xml --coverage-text

# configure notifications (email, IRC, campfire etc)
notifications:
  irc: "irc.freenode.org#yourfavouriteroomfortravis"

```

**Comment by ljmf00** [comment]
# Resources
- https://docs.travis-ci.com/
- https://travis-ci.org/

**Comment by ljmf00** [comment]
# MariaDB Before-Script
``` sh
sudo service mysql stop

sudo apt-get install python-software-properties
sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xcbcb082a1bb943db
sudo add-apt-repository 'deb http://ftp.osuosl.org/pub/mariadb/repo/5.5/ubuntu precise main'      # or any mirror located in US
sudo apt-get update
sudo apt-get install mariadb-server
```

**Comment by ljmf00** [comment]
# PHP travis-ci example

For .travis-ci.yml file build, follow this file example:
``` yml
# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to 5.2.17
  - 5.2
  # aliased to 5.3.29
  - 5.3
  # aliased to a recent 5.4.x version
  - 5.4
  # aliased to a recent 5.5.x version
  - 5.5
  # aliased to a recent 5.6.x version
  - 5.6
  # aliased to a recent 7.x version
  - 7.0
  # aliased to a recent hhvm version
  - hhvm

# optionally specify a list of environments, for example to test different RDBMS
env:
  - DB=mysql
  - DB=pgsql

# optionally set up exclutions and allowed failures in the matrix
matrix:
  exclude:
    - php: hhvm
      env: DB=pgsql  # PDO driver for pgsql is unsupported by HHVM (3rd party install for support)
  allow_failures:
    - php: 7.0
    - php: hhvm

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS hello_world_test;" -U postgres; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database hello_world_test;" -U postgres; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hello_world_test;" -uroot; fi

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: phpunit --configuration phpunit_$DB.xml --coverage-text

# configure notifications (email, IRC, campfire etc)
notifications:
  irc: "irc.freenode.org#yourfavouriteroomfortravis"

```
